import React from 'react';
import {
  Apple,
  ArrowDown,
  AtSign,
  Ghost,
  Music,
  ArrowLeft,
  ArrowUp,
  Bell,
  CalendarDays,
  ChartNoAxesColumnIncreasing,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleGauge,
  Clock,
  Coffee,
  CookingPot,
  Crown,
  CupSoda,
  Dumbbell,
  Eye,
  EyeOff,
  Flame,
  Gem,
  Gift,
  Goal,
  GraduationCap,
  HandPlatter,
  Hourglass,
  House,
  Info,
  Lightbulb,
  LogOut,
  MapPin,
  Medal,
  MessageCircle,
  Minus,
  Moon,
  MoreHorizontal,
  PartyPopper,
  Pencil,
  Plus,
  QrCode,
  RotateCcw,
  Salad,
  Search,
  Send,
  Settings,
  Soup,
  Sparkles,
  Star,
  Sun,
  Sunrise,
  Swords,
  Target,
  ThumbsUp,
  Trash2,
  TriangleAlert,
  Trophy,
  TrendingDown,
  TrendingUp,
  UserRound,
  UsersRound,
  Utensils,
  X,
  Zap,
} from 'lucide-react-native';
import { Colors } from '../../theme';

const ICONS = {
  apple: Apple,
  // Linked-account icons. Lucide dropped its brand glyphs (there is no
  // Instagram/TikTok icon to import), so these are the closest semantic stand-ins
  // rather than logos — which also keeps us clear of each platform's trademark
  // rules about using their marks in another app's UI.
  instagram: AtSign,
  snapchat: Ghost,
  tiktok: Music,
  back: ArrowLeft,
  'arrow-down': ArrowDown,
  'arrow-up': ArrowUp,
  bell: Bell,
  calendar: CalendarDays,
  chart: ChartNoAxesColumnIncreasing,
  checkmark: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'circle-alert': CircleAlert,
  check: CircleCheck,
  century: CircleGauge,
  clock: Clock,
  coffee: Coffee,
  'meal-goal': CookingPot,
  crown: Crown,
  drink: CupSoda,
  protein: Dumbbell,
  eye: Eye,
  'eye-off': EyeOff,
  flame: Flame,
  gem: Gem,
  gift: Gift,
  solo: Goal,
  school: GraduationCap,
  'meal-plan': HandPlatter,
  hourglass: Hourglass,
  home: House,
  info: Info,
  idea: Lightbulb,
  'sign-out': LogOut,
  'map-pin': MapPin,
  medal: Medal,
  minus: Minus,
  moon: Moon,
  ellipsis: MoreHorizontal,
  party: PartyPopper,
  edit: Pencil,
  plus: Plus,
  qr: QrCode,
  repeat: RotateCcw,
  salad: Salad,
  search: Search,
  settings: Settings,
  bowl: Soup,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  sunrise: Sunrise,
  challenges: Swords,
  target: Target,
  reaction: ThumbsUp,
  trash: Trash2,
  warning: TriangleAlert,
  league: Trophy,
  trophy: Trophy,
  'trend-down': TrendingDown,
  'trend-up': TrendingUp,
  profile: UserRound,
  users: UsersRound,
  coach: MessageCircle,
  meal: Utensils,
  send: Send,
  close: X,
  bolt: Zap,
} as const;

export type AppIconName = keyof typeof ICONS;

interface AppIconProps {
  name: AppIconName;
  size?: number;
  color?: string;
  strokeWidth?: number;
  accessibilityLabel?: string;
}

/** The app's single semantic vector-icon layer. PixelFlame is the game-art exception. */
export default function AppIcon({
  name,
  size = 20,
  color = Colors.textSecondary,
  strokeWidth = 2,
  accessibilityLabel,
}: AppIconProps) {
  const Icon = ICONS[name];
  return (
    <Icon
      accessibilityLabel={accessibilityLabel}
      color={color}
      size={size}
      strokeWidth={strokeWidth}
    />
  );
}
